name: easytax
description: "EasyTax is our senior project that focuses on improving the Income Tax season experience."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  image_picker: ^1.0.5
  supabase_flutter: ^2.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.2
  ocr_scan_text: ^1.3.1
  cached_network_image: ^3.3.1
  json_theme: ^6.4.0
  image_cropper: ^5.0.1
  http: ^1.2.0
  intl: ^0.18.1
  fl_chart: ^0.67.0
  flutter_launcher_icons: ^0.13.1
  pdf: ^3.10.8
  printing: ^5.12.0
  syncfusion_flutter_xlsio: ^25.1.42
  open_file: ^3.3.2
  permission_handler: ^11.3.1
  #pdfx: ^2.6.0

  file_picker: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/icon.png
    - assets/theme.json

    # Add Text Files to read dinto our App
    - Tax-Forms/

